### ISSUE TITLE
Error on snmpv3   bulkwalk error (integer divide by zero)

### ISSUE THREAD

**Issue by toni-moreno** [soniah/gosnmp#61] opened 2016-04-04 13:05 UTC
Hi @soniah 

When doing the same query over snmpbulkwalk command I got the expected result.

```
[root@lab01 influxsnmp]# snmpbulkwalk -v 3 -u v3userauth -l authNoPriv -a MD5 -A v3passauth  192.168.1.99 ifName
IF-MIB::ifName.1 = STRING: lo
IF-MIB::ifName.2 = STRING: eth0
IF-MIB::ifName.3 = STRING: sit0
```

but fails when done with gosnmp with the following code

```
...
...

          UsmParams = &gosnmp.UsmSecurityParameters{
                                UserName:                 s.V3AuthUser,
                                AuthenticationProtocol:   authpmap[s.V3AuthProt],
                                AuthenticationPassphrase: s.V3AuthPass,
                                PrivacyProtocol:          gosnmp.NoPriv,
                                PrivacyPassphrase:        "",
                        }

...
...
                fmt.Printf("DEBUG: USMPARAMS %+v\n", *UsmParams)
                client = &gosnmp.GoSNMP{
                        Target:             hostIPs[0],
                        Port:               uint16(s.Port),
                        Version:            gosnmp.Version3,
                        Timeout:            time.Duration(s.Timeout) * time.Second,
                        Retries:            s.Retries,
                        SecurityModel:      gosnmp.UserSecurityModel,
                        MsgFlags:           gosnmp.AuthPriv,
                        SecurityParameters: UsmParams,
                }
                fmt.Printf("DEBUG: CLIENT %+v\n", *client)
...
 fmt.Println("Looking up column names for:", c.Host)
   pdus, err := client.BulkWalkAll(ifName)
        if err != nil {
                fatal("SNMP bulkwalk error", err)
        }

```
And with these paràmeters.

```
[snmp.hostsnmpv3c]

host = "hostsnmpv3c"
port = 161
timeout = 20
retries = 5
repeat = 0
#snmp version /auth params
snmpversion = "3"
v3seclevel = "AuthPriv"
#only needed if Auth v3 enabled
v3authuser = "v3userpriv"
v3authpass = "v3passpriv"
v3authprot = "MD5"
#only needed if Privacy v3 enabled
3privpass = "v3passenc"
v3privprot = "DES"
# runtime parameters
freq = 30
extratags = [ "tagA=4","tagB=5" ,"tagC=6" ]
debug  = true

```
we have the following error:

```
DEBUG: USMPARAMS {AuthoritativeEngineID: AuthoritativeEngineBoots:0 AuthoritativeEngineTime:0 UserName:v3userauth AuthenticationParameters: PrivacyParameters:[] AuthenticationProtocol:2 PrivacyProtocol:1 AuthenticationPassphrase:v3passauth PrivacyPassphrase: localDESSalt:0 localAESSalt:0}
DEBUG: CLIENT {Target:192.168.1.99 Port:161 Version:3 Community: Timeout:20s Retries:5 Logger:<nil> loggingEnabled:false MsgFlags:3 SecurityModel:3 SecurityParameters:0xc820199c20 ContextEngineID: ContextName: Conn:<nil> MaxRepetitions:0 NonRepeaters:0 requestID:0 random:<nil> msgID:0}
Looking up column names for: hostsnmpv3b
Packet sanity verified, we got all the bytes (117)
parseRawField: version
0       02 01 03 30 11 02 04 0f
8       51 4d a3 02 03 00 ff e3
Parsed version 3
parseRawField: msgID
0       02 04 0f 51 4d a3 02 03
8       00 ff e3 04 01 00 02 01
Parsed message ID 256986531
parseRawField: maxMsgSize
0       02 03 00 ff e3 04 01 00
8       02 01 03 04 23 30 21 04
parseRawField: msgFlags
0       04 01 00 02 01 03 04 23
8       30 21 04 11 80 00 1f 88
parsed msg flags
parseRawField: msgSecurityModel
0       02 01 03 04 23 30 21 04
8       11 80 00 1f 88 80 30 3c
Parsed security model 3
parseRawField: msgAuthoritativeEngineID
0       04 11 80 00 1f 88 80 30
8       3c a3 16 68 42 ff 56 00
Parsed authoritativeEngineID ▒▒▒0<▒hB▒V
parseRawField: msgAuthoritativeEngineBoots
0       02 01 0c 02 03 03 17 0a
8       04 00 04 00 04 00 30 36
Parsed authoritativeEngineBoots 12
parseRawField: msgAuthoritativeEngineTime
0       02 03 03 17 0a 04 00 04
8       00 04 00 30 36 04 11 80
Parsed authoritativeEngineTime 202506
parseRawField: msgUserName
0       04 00 04 00 04 00 30 36
8       04 11 80 00 1f 88 80 30
Parsed userName
parseRawField: msgAuthenticationParameters
0       04 00 04 00 30 36 04 11
8       80 00 1f 88 80 30 3c a3
Parsed authenticationParameters
parseRawField: msgPrivacyParameters
0       04 00 30 36 04 11 80 00
8       1f 88 80 30 3c a3 16 68
Parsed privacyParameters
parseRawField: contextEngineID
0       04 11 80 00 1f 88 80 30
8       3c a3 16 68 42 ff 56 00
Parsed contextEngineID ▒▒▒0<▒hB▒V
parseRawField: contextName
0       04 00 a8 1f 02 04 d7 f0
8       ab bd 02 01 00 02 01 00
Parsed contextName
SNMP Packet is GET RESPONSE
0       a8 1f 02 04 d7 f0 ab bd
8       02 01 00 02 01 00 30 11
getResponseLength: 33
parseRawField: request id
0       02 04 d7 f0 ab bd 02 01
8       00 02 01 00 30 11 30 0f
requestID: 3622874045
parseRawField: error-status
0       02 01 00 02 01 00 30 11
8       30 0f 06 0a 2b 06 01 06
errorStatus: 0
parseRawField: error index
0       02 01 00 30 11 30 0f 06
8       0a 2b 06 01 06 03 0f 01
error-index: 0

=== unmarshalVBL()
0       30 11 30 0f 06 0a 2b 06
8       01 06 03 0f 01 01 04 00
16      30 11 30
vblLength: 19

STARTING a varbind. Cursor 2
0       30 0f 06 0a 2b 06 01 06
8       03 0f 01 01 04 00 41 01
16      30
parseRawField: OID
0       06 0a 2b 06 01 06 03 0f
8       06 0a 2b 06 01 06 03
OID: .1.3.6.1.6.3.15.1.1.4.0
decodeValue: value
0       41 01 42
decodeValue: type is Counter32
decodeValue: value is 0x42
2016/04/04 14:48:24 SNMP bulkwalk error recover: runtime error: integer divide by zero

```
Can you help me to understand which is the problem?

Thank you very much

**Comment by soniah** [comment] 2016-04-04 14:33
:+1:

**Comment by wdreeveii** [comment] 2016-04-04 17:39
After a quick review of the source code, I was unable to locate a likely
source for this problem.

Do you think you could pin point where in the call graph this is blowing up?

On Mon, Apr 4, 2016 at 6:33 AM, Sonia Hamilton <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/soniah/gosnmp/issues/61#issuecomment-205323818>
>



-- 
Whitham D. Reeve II
907-764-5263

**Comment by toni-moreno** [comment] 2016-04-04 21:15
Hi @wdreeveii ,@sonia. I've done all the test again , And the problem happens only with security level "NoAuthNoPriv"  and"AuthNoPriv" .

With security level "AuthPriv" the code works ok.

You can see current code here:

https://github.com/toni-moreno/influxsnmp/tree/added_snmpv3_support

Here one example of snmpwalk with 2 host snmp version 2c and other with snmpv3 with security mode AuthPriv.

````
[snmp.hostsnmpv3c]
#conection parameters
host = "hostsnmpv3c"
port = 161
timeout = 20
retries = 5
repeat = 0
#snmp version /auth params
snmpversion = "3"
v3seclevel = "AuthPriv"
#only needed if Auth v3 enabled
v3authuser = "v3userpriv"
v3authpass = "v3passpriv"
v3authprot = "MD5"
#only needed if Privacy v3 enabled
v3privpass = "v3passenc"
v3privprot = "DES"
````

````

[root@lab01 influxsnmp]# ./influxsnmp -names

SNMP host: 127.0.0.1
=========================================
lo .1.3.6.1.2.1.31.1.1.1.1.1
eth0 .1.3.6.1.2.1.31.1.1.1.1.2

SNMP host: hostsnmpv2_2
=========================================
lo .1.3.6.1.2.1.31.1.1.1.1.1
eth0 .1.3.6.1.2.1.31.1.1.1.1.2

SNMP host: hostsnmpv3c
=========================================
2016/04/04 22:54:19 Selected SI Auth - Priv
lo .1.3.6.1.2.1.31.1.1.1.1.1
eth0 .1.3.6.1.2.1.31.1.1.1.1.2
sit0 .1.3.6.1.2.1.31.1.1.1.1.3
````
Here with AuthNoPriv example config
```
[snmp.hostsnmpv3b]
#conection parameters
host = "hostsnmpv3b"
port = 161
timeout = 20
retries = 5
repeat = 0
#snmp version /auth params
snmpversion = "3"
v3seclevel = "AuthNoPriv"
#only needed if Auth v3 enabled
v3authuser = "v3userauth"
v3authpass = "v3passauth"
v3authprot = "MD5"
```

Here the output.

````
[root@grafanalab01 influxsnmp]# ./influxsnmp -names -verbose
Looking up column names for: 127.0.0.1 NAMES 1.3.6.1.2.1.31.1.1.1.1
COLUMNS [ifHCInOctets ifHCInUcastPkts ifHCOutOctets ifHCOutUcastPkts]
[1.3.6.1.2.1.31.1.1.1.6 1.3.6.1.2.1.31.1.1.1.7 1.3.6.1.2.1.31.1.1.1.10 1.3.6.1.2.1.31.1.1.1.11]
Looking up column names for: hostsnmpv2_2 NAMES 1.3.6.1.2.1.31.1.1.1.1
COLUMNS [ifHCInOctets ifHCInUcastPkts ifHCOutOctets ifHCOutUcastPkts]
[1.3.6.1.2.1.31.1.1.1.6 1.3.6.1.2.1.31.1.1.1.7 1.3.6.1.2.1.31.1.1.1.10 1.3.6.1.2.1.31.1.1.1.11]
2016/04/04 23:02:51 Selected SI Auth - No Priv
Looking up column names for: hostsnmpv3b NAMES 1.3.6.1.2.1.31.1.1.1.1
2016/04/04 23:02:51 SNMP bulkwalk error recover: runtime error: integer divide by zero
````

I don't know any better way to debug the exact point where code does "divide by zero", I'm still a beginner in the goland world. 
But  snmpbulkwalk command is working with these parameters.

```` 
[root@grafanalab01 influxsnmp]# snmpwalk -v 3 -u v3userauth -l authNoPriv -a MD5 -A v3passauth  192.168.1.99 ifName
IF-MIB::ifName.1 = STRING: lo
IF-MIB::ifName.2 = STRING: eth0
IF-MIB::ifName.3 = STRING: sit0
```

What can I do?  There is any way to get a stacktrace in a easy way? I have tested unsuccessfully with this lib https://github.com/go-errors/errors . 

Do you know any other way?

**Comment by wdreeveii** [comment] 2016-04-05 10:11
I nailed down that the divide by zero error is caused by a mod on a password field that is only dealt with when the security level is set to authpriv. I couldn't figure out why that code was enabled when you were doing auth only requests until I looked at your code.

https://github.com/toni-moreno/influxsnmp/blob/added_snmpv3_support/snmp.go#L302

You only ever pass the security mode as AuthPriv. Naturally all communication will then get performed in the AuthPriv security level, even if you don't provide a password.

I think the real failure here on gosnmp's part is that these params were not validated for sanity up front. A situation I will soon remedy.

**Comment by toni-moreno** [comment] 2016-04-05 11:51
@wdreeveii Thank you very much !!! And sorry for this terrible mistake

I've solved it and , tested successfully  with snmpv2 and snmpv3 with the 3 security Levels. 

````
[root@lab01 influxsnmp]# ./influxsnmp -names

SNMP host: 127.0.0.1
=========================================
lo .1.3.6.1.2.1.31.1.1.1.1.1
eth0 .1.3.6.1.2.1.31.1.1.1.1.2

SNMP host: hostsnmpv2_2
=========================================
lo .1.3.6.1.2.1.31.1.1.1.1.1
eth0 .1.3.6.1.2.1.31.1.1.1.1.2

SNMP host: hostsnmpv3a
=========================================
lo .1.3.6.1.2.1.31.1.1.1.1.1
eth0 .1.3.6.1.2.1.31.1.1.1.1.2
sit0 .1.3.6.1.2.1.31.1.1.1.1.3

SNMP host: hostsnmpv3b
=========================================
lo .1.3.6.1.2.1.31.1.1.1.1.1
eth0 .1.3.6.1.2.1.31.1.1.1.1.2
sit0 .1.3.6.1.2.1.31.1.1.1.1.3

SNMP host: hostsnmpv3c
=========================================
lo .1.3.6.1.2.1.31.1.1.1.1.1
eth0 .1.3.6.1.2.1.31.1.1.1.1.2
sit0 .1.3.6.1.2.1.31.1.1.1.1.3
````

**Comment by soniah** [comment] 2016-04-05 12:14
Thanks @toni-moreno 

Reopened, as I imagine @wdreeveii is going to submit a patch :-)

**Comment by soniah** [comment] 2016-08-06 00:22
@wdreeveii poke :-)

**Comment by wdreeveii** [comment] 2016-09-01 09:26
I have committed code to validate parameters so this cannot happen any more.

**Closed by wdreeveii** 2016-09-01 09:26 UTC
